name: Trigger cache request

on:
  workflow_dispatch:
  schedule:
    # At minute 33 past every 3rd hour. (https://crontab.guru/#33_*/3_*_*_*)
    - cron: '33 */3 * * *'

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: HTTP request to cache endpoint
        id: cacheRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://moviefeed.ishetaldonderdag.nl/api/v1/cache'
          method: 'GET'
          timeout: 10000
          customHeaders: '{
            "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
          }'
